DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS promos;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS organizers;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS postgis;
DROP TYPE IF EXISTS events_visability_enum;
