version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "uevent"
      POSTGRES_USER: "uevent"
      POSTGRES_PASSWORD: "uevent"
    ports:
      - '5932:5432'