version: '3.0'
services:
  uevent-api:
    image: kevandee/uevent-api:0.0.3
    restart: always
    depends_on:
      - postgres
    env_file:
      - '.env'
    ports:
      - '4000:3000'
  postgres:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: "uevent"
      POSTGRES_USER: "uevent"
      POSTGRES_PASSWORD: "uevent"
    ports:
      - '5932:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  webclient:
    image: kevandee/uevent-web-client:0.0.2
    restart: always
    depends_on: 
      - uevent-api
    ports:
      - '81:3000'
volumes:
  pgdata: